export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILER_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
    PROFILE_BLOG_DELETED: "PROFILE_BLOG_DELETED",
  },

  blog: {
    DATA_FETCHING: "BLOG_DATA_FETCHING",
    DATA_FETCHED: "BLOG_DATA_FETCHED",
    DATA_FETCH_ERROR: "BLOG_DATA_FETCH_ERROR",
    DATA_EDITED: "BLOG_DATA_EDITED",
    DATA_CREATED: "BLOG_DATA_CREATED",
    BLOG_DELETED: "BLOG_DATA_DELETED",
  },
};
